version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql  
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"  
    volumes:
      - mysql_data:/var/lib/mysql 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/DockerCRUD 
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""  
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data:
